module.exports.Services=require('./')
module.exports.AdminControlller=require('./adminControlller')
module.exports.AuthController = require('./authController')
module.exports.BuyerController = require('./buyerController')
module.exports.MessageController = require('./messageController')
module.exports.PlantController = require('./plantController')
module.exports.SellerController = require('./sellerController')
module.exports.UserController = require('./userController')
